<a href="https://colab.research.google.com/github/gazza-bot/AdilDev_Porto/blob/main/Data_Cleansing__MCD_Review.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install Sastrawi

Collecting Sastrawi
  Downloading Sastrawi-1.0.1-py2.py3-none-any.whl.metadata (909 bytes)
Downloading Sastrawi-1.0.1-py2.py3-none-any.whl (209 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.7/209.7 kB 3.2 MB/s eta 0:00:00
Installing collected packages: Sastrawi
Successfully installed Sastrawi-1.0.1

In [5]:
import pandas as pd
import re
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
from google.colab import drive

# initialize folders and drive
drive.mount('/content/drive')
folder_path = '/content/drive/MyDrive/KERIS-Coba/Scrap-Kopken'
file_path = '/content/drive/MyDrive/KERIS-Coba/Scrap-Kopken/LOW_Resto_MCD_review.csv'

# load dataset
df = pd.read_csv(file_path)
df.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,d6e5fe01-f639-41d8-b9d3-04aaa7238767,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,t ?,5,0,3.51.0,2026-10-20 11:13:26,NaN,NaN,3.51.0
1,f93448dc-c3a0-4bf0-bcda-bf54cd3a1fc7,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"aplikasi kaga bisa dibuka, something went wron...",1,0,NaN,2026-10-18 04:49:50,NaN,NaN,NaN
2,a3d6802a-35a7-4490-b4be-66a18e4f849c,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,"pesen drive thru petugas gak nyaut, waktunya h...",1,0,3.49.0,2026-10-17 10:36:32,NaN,NaN,3.49.0
3,e0088fb8-be04-4f5b-b321-8c07cf0a0d61,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,67⁹⁷,4,0,3.51.0,2026-10-17 07:03:21,NaN,NaN,3.51.0
4,40da3d65-a6f8-42c6-bc2a-1fcb28864e9c,Pengguna Google,https://play-lh.googleusercontent.com/EGemoI2N...,apalikaai tolol,1,0,3.51.0,2026-10-17 04:54:28,NaN,NaN,3.51.0

Drop Kolom yang tidak dipakai

In [6]:
drop_columns = ['userName', 'userImage', 'reviewCreatedVersion', 'repliedAt', 'at']
df = df.drop(columns=drop_columns, errors='ignore')

df.head()

,reviewId,content,score,thumbsUpCount,replyContent,appVersion
0,d6e5fe01-f639-41d8-b9d3-04aaa7238767,t ?,5,0,NaN,3.51.0
1,f93448dc-c3a0-4bf0-bcda-bf54cd3a1fc7,"aplikasi kaga bisa dibuka, something went wron...",1,0,NaN,NaN
2,a3d6802a-35a7-4490-b4be-66a18e4f849c,"pesen drive thru petugas gak nyaut, waktunya h...",1,0,NaN,3.49.0
3,e0088fb8-be04-4f5b-b321-8c07cf0a0d61,67⁹⁷,4,0,NaN,3.51.0
4,40da3d65-a6f8-42c6-bc2a-1fcb28864e9c,apalikaai tolol,1,0,NaN,3.51.0

In [12]:
missing_values = df['content'].isna().sum()
print(f"Jumlah Missing values : {missing_values}")

duplicate_values = df.duplicated(subset=['content']).sum()
print(f"Jumlah data yang terduplikat : {duplicate_values}")

Jumlah Missing values : 0
Jumlah data yang terduplikat : 2297

In [14]:
from collections import Counter

teks = " ".join(df['content'].astype(str).str.lower())
hitung = Counter(teks.split())

print("100 kata terbanyak:")
print(hitung.most_common(100))
print("=" * 36)
print("100 kata tersedikit:")
print(hitung.most_common()[-100:])

100 kata terbanyak:
[('di', 1737), ('bisa', 1599), ('aplikasi', 1511), ('ga', 898), ('tidak', 867), ('dan', 866), ('nya', 818), ('saya', 774), ('gak', 707), ('ini', 655), ('mcd', 636), ('ada', 636), ('promo', 591), ('yg', 574), ('good', 560), ('bagus', 558), ('mau', 539), ('sangat', 539), ('ok', 430), ('yang', 405), ('tapi', 399), ('aja', 396), ('banyak', 392), ('mantap', 386), ('banget', 357), ('padahal', 351), ('udah', 348), ('aplikasinya', 332), ('malah', 326), ('sudah', 323), ('ke', 320), ('buat', 301), ('lebih', 296), ('sama', 289), ('lagi', 285), ('apk', 281), ('pake', 278), ('kenapa', 264), ('login', 254), ('gk', 248), ('tolong', 242), ('untuk', 239), ('jadi', 234), ('baru', 229), ('pas', 227), ('masuk', 223), ('gabisa', 221), ('update', 219), ('baik', 214), ('menu', 214), ('terus', 213), ('ya', 211), ('download', 211), ('hp', 210), ('sering', 206), ('selalu', 205), ('dengan', 204), ('pesan', 203), ('udh', 200), ('suka', 197), ('app', 197), ('dari', 197), ('error', 196), ('juga', 194), ('beli', 192), ('makan', 188), ('kalo', 177), ('membantu', 175), ('promonya', 174), ('pelayanan', 174), ('buka', 172), ('susah', 169), ('bgt', 169), ('harga', 168), ('bikin', 166), ('poin', 166), ('lama', 164), ('enak', 164), ('kok', 164), ('harus', 163), ('email', 163), ('sekali', 161), ('tp', 160), ('kasih', 156), ('apa', 155), ('makanan', 152), ('coba', 152), ('d', 151), ('dibuka', 149), ('aku', 148), ('pakai', 146), (',', 146), ('eror', 143), ('ribet', 141), ('1', 141), ('ayam', 141), ('murah', 138), ('masih', 133), ('itu', 133), ('daftar', 128)]
====================================
100 kata tersedikit:
[('(2', 1), ('porsi)', 1), ('drink', 1), ('logika', 1), ('gratisnya,', 1), ('discountnya..', 1), ('oke...', 1), (':ayam', 1), ('2,tea', 1), ('75', 1), ('rb...gileee...langsung', 1), ('uninstal..merasa', 1), ('tertipu..#cimahi', 1), ('cantum', 1), ('hemat.maju', 1), ('hooo', 1), ('🤤🤤🤤', 1), ('thai', 1), ('diseluru', 1), ('🤩🤗😘😍', 1), (':((', 1), ('code.', 1), ('...alamat', 1), ('betul..gimana', 1), ('makasi,', 1), ('puass..', 1), ('promonnya,', 1), ('jelekk', 1), ('gilaaaa', 1), ('nya..ini', 1), ('suka..', 1), ('kuota,', 1), ('promo,menu', 1), ('amsong.', 1), ('wahhhhhhh', 1), ('bbbbbbbaaaaaggggggusssss', 1), ('rumah....ilove', 1), ('memuaskan.saya', 1), ('free.', 1), ('wr.wb.perkenalkan', 1), ('nur', 1), ('jannah', 1), ('entar', 1), ('mei.saya', 1), ('7smp,ok', 1), ('aja.jadi', 1), ('bisa?makannya', 1), ('1.asli', 1), ('bangsat.padahal', 1), ('murah!!!dan', 1), ('enak!!?tapi', 1), ('usul', 1), ('lahu', 1), ('diptonng', 1), ('aa', 1), ('nn', 1), ('berlatit', 1), ('tfk', 1), ('deperti', 1), ('lagu', 1), ('enriy', 1), ('hsd', 1), ('kuass', 1), ('hun', 1), ('sla.anidoa', 1), ('lshu', 1), ('iyu', 1), ('fpy', 1), ('nintang', 1), ('tigs', 1), ('🚸', 1), ('iyes', 1), ('tanga', 1), ('sholattarawihi', 1), ('ngabuburit', 1), ('biasa,murahnya', 1), ('marthw', 1), ('koyo', 1), ('ulo', 1), ('lago', 1), ('bre', 1), ('terbaik.', 1), ('safety.', 1), ('mantappppp', 1), ('pula,', 1), ('quality', 1), ('kekinian', 1), ('banget😍', 1), ('pon', 1), ('xbtul', 1), ('pahit', 1), ('xde', 1), ('rsa', 1), ('mnis', 1), ('gi', 1), ('straw', 1), ('bgi', 1), ('xbgus', 1), ('boleh.', 1), ('terbaik......', 1)]

In [15]:
# Jumlah data sebelum di drop duplikat
print(f"Jumlah data (Sebelum drop): {df.shape[0]}")
# Drop cells duplicate
df = df.drop_duplicates(subset=['content'], keep='first')
print("Data duplikat berhasil dihapus")

# Jumlah data
print(f"Jumlah data (Setelah drop): {df.shape[0]}")

Jumlah data (Sebelum drop): 9629
Data duplikat berhasil dihapus
Jumlah data (Setelah drop): 7332

In [20]:
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory

# 1. Stopwords: jaga kata negasi & penguat
stop_words = StopWordRemoverFactory().get_stop_words()

jaga = {'tidak', 'tak', 'bukan', 'belum', 'kurang', 'jangan', 'sangat', 'lain', 'bisa'}
stop_words = [w for w in stop_words if w not in jaga]
stop_words.extend(['nya', 'sih', 'dong', 'deh', 'ya', 'kan'])
stop_words = set(stop_words)  # set lebih cepat

# 2. Kamus slang (tambahkan sesuai temuan di datamu)
slang_dict = {
    "bgs": "bagus", "bgt": "banget", "gk": "tidak", "ga": "tidak", "gak": "tidak",
    "apk": "aplikasi", "sy": "saya", "klo": "kalau", "udh": "sudah",
    "tp": "tapi", "dpt": "dapat", "knp": "kenapa", "yg": "yang", "gmn": "bagaimana",
    "mantab": "mantap", "rekomended": "direkomendasikan", "pass": "pas",
    "dilidah": "di lidah", "mw" : "mau", "kalo": "kalau", "udah": "sudah",
    "pake": "pakai","dapet": "dapat","jd": "jadi","pesen": "pesan",
    "app": "aplikasi", "thn": "tahun","dgn": "dengan","ny": "nya","inget": "ingat",
    "recomend": "rekomendasi","gabisa": "tidak bisa","gbs": "tidak bisa",
    "eror": "error", "kalo": "kalau", "udah": "sudah","pake": "pakai","app": "aplikasi","d": "di",
    "endul": "enak","mantul": "mantap","n": "dan", "jelekk" : "jelek", "puass" : "puas", "apalikaai" : "aplikasi"
}

def normalisasi_teks(text):
    text = str(text).lower()
    text = re.sub(r'http\S+|www\S+', '', text)
    text = re.sub(r'(.)\1{2,}', r'\1', text)
    text = re.sub(r'[^a-z\s]', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()

    words = text.split()
    words = [slang_dict.get(w, w) for w in words]
    words = [w for w in words if w not in stop_words]
    return " ".join(words)

# 3. Terapkan
df['clean_data'] = df['content'].apply(normalisasi_teks)
df['clean_data'] = df['clean_data'].replace('', pd.NA)
df = df.dropna(subset=['clean_data']).copy()

# 4. Label sentimen dari rating
def beri_label(score):
    if score <= 2:
        return 'negatif'
    elif score == 3:
        return 'netral'
    return 'positif'

df['label'] = df['score'].apply(beri_label)

# 5. Cek hasil
print(df[['content', 'clean_data', 'score', 'label']].head())
print("Value Counts : ", df['label'].value_counts())

# 6. Simpan (kolom content asli tetap ada)
df.to_csv('/content/drive/MyDrive/KERIS-Coba/Scrap-Kopken/cleaned_app_reviews_MCD.csv', index=False)
print("Pembersihan selesai dan data telah disimpan!")

                                             content  \
0                                                t ?
1  aplikasi kaga bisa dibuka, something went wron...
2  pesen drive thru petugas gak nyaut, waktunya h...
4                                    apalikaai tolol
5  tolong ditambahkan fitur riwayat transaksi kit...

                                          clean_data  score    label
0                                                  t      5  positif
1  aplikasi kaga bisa dibuka something went wrong...      1  negatif
2  pesan drive thru petugas tidak nyaut waktunya ...      1  negatif
4                                     aplikasi tolol      1  negatif
5  ditambahkan fitur riwayat transaksi visit stor...      3   netral
Value Counts :  label
negatif    3831
positif    3062
netral      318
Name: count, dtype: int64
Pembersihan selesai dan data telah disimpan!